### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by Narven** [craigemery/vim-autotag#23]
Hi, when I run vim, I'm getting this error:

```
 vim README.markdown
Error detected while processing /Users/pedromsluz/.vim/bundle/vim-autotag/plugin/autotag.vim:
line   25:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pedromsluz/.vim/bundle/vim-autotag/plugin/autotag.py", line 11, in <module>
    import logging
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Press ENTER or type command to continue
```

Any ideas?

`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 18:37:46)`

**Comment by padi** [comment]
I just ran into this recently, but only when using vim for crafting git commits (I have $VISUAL and $EDITOR set to `nvim -n` (neovim).

I also recently updated my python_host_prog and python3_host_prog since I updated homebrew not too long ago after I saw this same issue.

```vim
if has('nvim')
  let g:python_host_prog  = '/usr/local/bin/python2'
  let g:python3_host_prog = '/usr/local/bin/python3'
endif
```

**Comment by preist** [comment]
But how do you fix this for `vim`?

**Comment by Narven** [comment]
@preist for me I manage to fix it by going into the installation folder of `vim-autotag` and deleted manually the folder. then went to vim... commented the install line `Plugin 'craigemery/vim-autotag'` and ran `:PluginClean` then removed the comment and ran `PluginInstall`, after that all was working.

**Comment by craigemery** [comment]
If you've done a clean and then a re-install I suspect there's a .pyc file involved that was no longer compatible as your Python had changed.
But it's a guess.

**Comment by preist** [comment]
I caused this by running `brew install python3`. The way I fixed the problem was to make Python 3 my default system python. The fastest, easiest way for me was to create an alias inside my `.bashrc` file like this:

```bash
alias python='python3'
```

It fixed the errors for Vim. Do you see any problems with my approach?

Thanks @Narven @craigemery
