### ISSUE TITLE
Tags file not updating

### ISSUE THREAD

**Issue by alalfakawma** [craigemery/vim-autotag#25]
Hello, my tags file is not updating, I have a Laravel project and after running `php artisan make:model Test`, I don't see this Model being registered/appended to the tags file and my php namespace plugin does not detect it. Can you help me figure this out, here is the configs I have added 

```vim
let g:autotagTagsFile=".tags"
let g:autotagmaxTagsFileSize=10
let g:autotagCtagsCmd="ctags -R -f .tags --PHP-kinds=cfi --languages=php"
```

**Comment by craigemery** [comment]
I'm sorry I've never worked with PHP and have no idea where to start on this.
But there is debugging in my script. Try using :call AutoTagDebug()

**Comment by craigemery** [comment]
Looking again I see you're supplying a tags file argument.
The entire point of my plugin is to locate the tags file for you and run ctags on your behalf. The variable g:autotagCtagsCmd is only for the path of the ctags binary. The command is built up with other arguments that includes the name of the output tags file. I'd use your ~/.ctags to direct the kind of output. g:autotagCtagsCmd should only be used if ctags.exe isn't in the PATH.

**Comment by kozikowskik** [comment]
Hi, @alalfakawma your tags file is not generated because of g:autotagmaxTagsFileSize. You set it to 10 bytes. The default value for g:autotagmaxTagsFileSize is **1024 * 1024 * 7** it's 7 MB. Additionally, if you want to add some custom params to ctags command you have to omit the -f switch coz it's a part of command template in autotag code. In your case it should look like that **g:autotagCtagsCmd="ctags -R --languages=php --php-kinds=cfi"**

**Comment by alalfakawma** [comment]
> Hi, @alalfakawma your tags file is not generated because of g:autotagmaxTagsFileSize. You set it to 10 bytes. The default value for g:autotagmaxTagsFileSize is **1024 * 1024 * 7** it's 7 MB. Additionally, if you want to add some custom params to ctags command you have to omit the -f switch coz it's a part of command template in autotag code. In your case it should look like that `g:autotagCtagsCmd="ctags -R --languages=php --php-kinds=cfi"`

Okay, sounds fair. I'll try something like this, but the max file size was never said to be in bytes? I thought it was in MB's.

**Comment by kozikowskik** [comment]
> Okay, sounds fair. I'll try something like this, but the max file size was never said to be in bytes? I thought it was in MB's.
Yeah, that's true there is nothing in the docs. 

@craigemery it's a good idea to add this information to the docs.

**Comment by craigemery** [comment]
README has been updated.
The cap on the tags file size is there to stop Vim drowning in the "patching" of a massive pre-existing tags file. Perhaps an async task would make that easier to cope with.

**Comment by greglund** [comment]
FYI, if anyone got here because they were searching for g:autotagmaxTagsFileSize, it has been deprecated as of this commit: https://github.com/craigemery/vim-autotag/commit/b7a26f6004635ca1053f69b8fc9644e388b6f3a6

**Comment by benittobeny34** [comment]
> @alalfakawma  Okay, sounds fair. I'll try something like this, but the max file size was never said to be in bytes? I thought it was in MB's. Also, the reason why I have the -f switch is because my tags file name is .tags and is hidden.

what did you updated, for me it's not working. could you please help. when i am manually run ctags it working.

**Comment by alalfakawma** [comment]
> > @alalfakawma  Okay, sounds fair. I'll try something like this, but the max file size was never said to be in bytes? I thought it was in MB's. Also, the reason why I have the -f switch is because my tags file name is .tags and is hidden.
> 
> what did you updated, for me it's not working. could you please help. when i am manually run ctags it working.

Hello, i'm really sorry, this is a really old post and I do not use ctags anymore and i'm not really sure what I had done to fix this issue.

@benittobeny34
