### ISSUE TITLE
AttributeError: 'module' object has no attribute 'set_executable' when launching Vim

### ISSUE THREAD

**Issue by giddie** [craigemery/vim-autotag#30]
When launching Vim or NeoVim, I get the following error message:

```
Error detected while processing function provider#python#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python2-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dannpg/.vim-config/vim-dir/vim-plug/vim-autotag/plugin/autotag.py", line 52, in <module>
    fix_multiprocessing()
  File "/home/dannpg/.vim-config/vim-dir/vim-plug/vim-autotag/plugin/autotag.py", line 39, in fix_multiprocessing
    multiprocessing.set_executable(sys.executable)
AttributeError: 'module' object has no attribute 'set_executable'
```

I have removed everything apart from this plugin from my vimrc. NeoVim's `:checkhealth` shows a working Python2 and Python3, with latest pynvim installed for both.

**Comment by craigemery** [comment]
What version of Python are you using? I've not used neovim. I moved the tags clean & rebuild into a thread made using Python multiprocessing.

**Comment by craigemery** [comment]
I went through the Python docs on multiprocessing. set_executable() seems to be in all versions. I'm baffled why you're getting this error.

**Comment by joemiller** [comment]
I'm also getting this error with neovim, but I haven't been able to figure out why yet either. Sorry I can't add more than "me too" on this one.

**Comment by JohanGio92** [comment]
the same problem, In Vim works, but in Neovim doesn't

**Comment by giddie** [comment]
Python2: 2.7.17
Python2: 3.8.2

I'm on Archlinux.

**Comment by craigemery** [comment]
I'm guessing that in architectures that have spawn not set as the default method for making new processes, the executable cannot be set.
In that case, I'd hope that it's redundant & so doesn't need fixing. It only needs fixing in Vim as the executable is Vim itself and not Python. So I'll just catch the attribute error & see how that affects it running on those architectures. I've only got WSL as a Linux right now & it has a set_excutable() method.

**Comment by craigemery** [comment]
As of 49ea351 I think this should be a lot better.
Please have a look.

**Comment by joemiller** [comment]
@craigemery The error message is gone now

**Comment by giddie** [comment]
Yep; the error message has gone now :)

**Comment by craigemery** [comment]
Cool
