### ISSUE TITLE
Autotag on windows, vim portable

### ISSUE THREAD

**Issue by solra** [craigemery/vim-autotag#8]
In order to get autotag to work on gVim portable on windows, I had to make some small changes see the gist below.
https://gist.github.com/raduSolea/a9dbb238791f7eb942a5#file-autotag-vim

**Comment by craigemery** [comment]
A diff would have been better.
Is the HEAD working for you unchanged?

**Comment by craigemery** [comment]
Sorry, I clearly took so long to re-read this the gist has gone
